apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k3k.fullname" . }}
  labels:
    {{- include "k3k.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
     matchLabels:
      {{- include "k3k.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k3k.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets: {{- include "image.pullSecrets" (concat .Values.controller.imagePullSecrets .Values.global.imagePullSecrets) | nindent 8 }}
      containers:
        - image: "{{- include "controller.registry" .}}{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          name: {{ .Chart.Name }}
          {{- with .Values.controller.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
          - k3k
          - --cluster-cidr={{ .Values.host.clusterCIDR }}
          - --k3s-server-image={{- include "server.registry" .}}{{ .Values.server.image.repository }}
          - --k3s-server-image-pull-policy={{ .Values.server.image.pullPolicy }}
          - --shared-agent-image={{- include "agent.shared.registry" .}}{{ .Values.agent.shared.image.repository }}:{{ default .Chart.AppVersion .Values.agent.shared.image.tag }}
          - --shared-agent-image-pull-policy={{ .Values.agent.shared.image.pullPolicy }}
          - --virtual-agent-image={{- include "agent.virtual.registry" .}}{{ .Values.agent.virtual.image.repository }}
          - --virtual-agent-image-pull-policy={{ .Values.agent.virtual.image.pullPolicy }}
          - --kubelet-port-range={{ .Values.agent.shared.kubeletPortRange }}
          - --webhook-port-range={{ .Values.agent.shared.webhookPortRange }}
          {{- range $key, $value := include "image.pullSecrets" (concat .Values.agent.imagePullSecrets .Values.global.imagePullSecrets) | fromYamlArray }}
          - --agent-image-pull-secret
          - {{ .name }}
          {{- end }}
          {{- range $key, $value := include "image.pullSecrets" (concat .Values.server.imagePullSecrets .Values.global.imagePullSecrets) | fromYamlArray }}
          - --server-image-pull-secret
          - {{ .name }}
          {{- end }}
          env:
          - name: CONTROLLER_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          {{- with .Values.controller.extraEnv }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          ports:
          - containerPort: 8080
            name: https
            protocol: TCP
          - containerPort: 9443
            name: https-webhook
            protocol: TCP
      serviceAccountName: {{ include "k3k.serviceAccountName" . }}
