#!/bin/bash

set -eo pipefail

SCRIPT_ROOT=$(dirname "${BASH_SOURCE[0]}")

if [[ -z ${VERSION} ]]; then
    echo "version unbound"
    VERSION=$(${SCRIPT_ROOT}/version)
fi

LDFLAGS="-X \"github.com/rancher/k3k/pkg/buildinfo.Version=${VERSION}\""

echo "Building k3k... [cli os/arch: ${HOST_GOOS}/${HOST_GOARCH}]"
echo "Current TAG: ${VERSION} "

export CGO_ENABLED=0
GOOS=linux GOARCH=amd64 go build -v -ldflags="${LDFLAGS}" -o bin/k3k
GOOS=linux GOARCH=amd64 go build -v -ldflags="${LDFLAGS}" -o bin/k3k-kubelet ./k3k-kubelet

# build the cli for the local OS and ARCH
GOOS=${HOST_GOOS} GOARCH=${HOST_GOARCH} go build -v -ldflags="${LDFLAGS}" -o bin/k3kcli ./cli
