name: Gorelease

on:
  release:
    types: [ deleted ]
  workflow_dispatch:
    inputs:
      registry:
        type: choice
        description: Select the container registry
        options:
        - dockerhub
        - ghcr.io

env:
    GH_TOKEN: ${{ github.token }}

permissions:
    contents: write
    id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
