name: Gorelease

on:
  release:
  push:
  workflow_dispatch:
    inputs:
      registry:
        type: choice
        description: Select the container registry
        options:
        - dockerhub
        - ghcr.io

env:
    GH_TOKEN: ${{ github.token }}

permissions:
    contents: write
    id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Check event
      run: echo "event_name=${{github.event_name}}"

    - name: Check if
      if: github.event == 'workflow_dispatch'
      run: echo "event_name=${{github.event_name}}"

    - name: Check if 2
      if: github.event_name == 'workflow_dispatch'
      run: echo "event_name=${{github.event_name}}"
    
    - name: Checkout code
      uses: actions/checkout@v4
