name: Gorelease Release

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Delete the specified tag

permissions:
    contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
