name: Conformance Tests

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
    contents: read

jobs:
  conformance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    
    - name: Validate
      run: make validate

    - name: Install hydrophone
      run: go install sigs.k8s.io/hydrophone@latest
    
    - name: Build and package
      run: |
        make build
        make package

        # add k3kcli to $PATH
        echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

    - name: Check k3kcli
      run: k3kcli -v

    - name: Run tests
      run: make test-conformance
      env:
        LOG_DIR: conformance-logs

    - name: Archive k3s logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: conformance-k3s-logs
        path: /tmp/k3s.log
    
    - name: Archive k3k logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: conformance-k3k-logs
        path: /tmp/k3k.log

    - name: Archive hydrophone logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: conformance-logs
        path: /tmp/conformance-logs/e2e.log

  sigs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tests:
          - name: k8s-io
            focus: '\[k8s\.io\]'
          - name: sig-api-machinery
            focus: '\[sig-api-machinery\]'
          - name: sig-apps
            focus: '\[sig-apps\]'
          - name: sig-architecture
            focus: '\[sig-architecture\]'
          - name: sig-auth
            focus: '\[sig-auth\]'
          - name: sig-cli
            focus: '\[sig-cli\]'
          - name: sig-instrumentation
            focus: '\[sig-instrumentation\]'
          - name: sig-network
            focus: '\[sig-network\]'
          - name: sig-node
            focus: '\[sig-node\]'
          - name: sig-scheduling
            focus: '\[sig-scheduling\]'
          - name: sig-storage
            focus: '\[sig-storage\]'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    
    - name: Validate
      run: make validate

    - name: Install hydrophone
      run: go install sigs.k8s.io/hydrophone@latest
    
    - name: Build and package
      run: |
        make build
        make package

        # add k3kcli to $PATH
        echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

    - name: Check k3kcli
      run: k3kcli -v

    - name: Run tests
      run: make test-conformance
      env:
        FOCUS: ${{ matrix.tests.focus }}
        LOG_DIR: ${{ matrix.tests.name }}

    - name: Archive k3s logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ matrix.tests.name }}-k3s-logs
        path: /tmp/k3s.log
    
    - name: Archive k3k logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ matrix.tests.name }}-k3k-logs
        path: /tmp/k3k.log

    - name: Archive hydrophone logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ matrix.tests.name }}-logs
        path: /tmp/${{ matrix.tests.name }}/e2e.log
