name: E2E

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
    contents: read

env:
  GO_VERSION: "1.22"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: ${{env.GO_VERSION}}

    - name: Install tools
      run: |
        go install github.com/onsi/ginkgo/v2/ginkgo
        go get github.com/onsi/gomega/...
        
        # kubectl
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

        #k3d
        wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

    - name: Setup cluster
      run: |
        k3d registry create registry.localhost --port 12345
        k3d cluster create --registry-use k3d-registry.localhost:12345 k3k
        echo "Waiting for node to be ready"
        kubectl wait --for=condition=Ready $(kubectl get nodes -o name)

    - name: Build
      run: |
        export CGO_ENABLED=0
        go build -o bin/k3k
        go build -o bin/k3k-kubelet ./k3k-kubelet
        go build -o bin/k3kcli ./cli
        sudo cp bin/k3kcli /usr/local/bin/k3kcli

    - name: Build and push images
      run: |
        docker build -f package/Dockerfile -t k3d-registry.localhost:12345/rancher/k3k:dev .
        docker push k3d-registry.localhost:12345/rancher/k3k:dev
        
        docker build -f package/Dockerfile.kubelet -t k3d-registry.localhost:12345/rancher/k3k:dev-kubelet .
        docker push k3d-registry.localhost:12345/rancher/k3k:dev-kubelet

    - name: Install k3k
      run: |
        helm upgrade --install \
          --set image.repository=k3d-registry.localhost:12345/rancher/k3k \
          --set image.tag=dev \
          --set sharedAgent.image.repository=k3d-registry.localhost:12345/rancher/k3k \
          --set sharedAgent.image.tag=dev-kubelet \
          k3k ./charts/k3k/

    - name: K3k
      run: |
        k3kcli cluster create --name sample --kubeconfig $HOME/.kube/config

    - name: Run tests
      run: |
        ginkgo run ./...
